//! Slack in your terminal, as yourself: the library behind the `slack` binary.
mod api;
mod app;
mod auth;
mod blocks;
mod cache;
pub mod cli;
pub mod commands;
mod config;
pub mod ctx;
mod emoji;
mod firehose;
mod fuzzy;
mod inbox;
mod markdown;
mod mrkdwn;
mod pattern;
mod permalink;
mod promises;
pub mod render;
mod resolve;
pub mod tui;
mod typesafe;
mod update;
mod version;
